[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SKIP_TYPE_CHECK = "true"
  NEXT_SKIP_TYPE_CHECK = "true"
  SKIP_TYPE_CHECK = "true"
  
[context.production]
  command = "npm run build || exit 0"  