[build]
  command = "npx cross-env NEXT_TELEMETRY_DISABLED=1 SKIP_TYPE_CHECK=true npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SKIP_TYPE_CHECK = "true"
  NEXT_SKIP_TYPE_CHECK = "true"
  SKIP_TYPE_CHECK = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "10"